blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/krugazul/skills-expand-your-team-with-copilot/blob/main/docs/how-to-develop.md
    about: Read the development guide for technical information
  - name: 💬 Discussion
    url: https://github.com/krugazul/skills-expand-your-team-with-copilot/discussions
    about: Ask questions and discuss ideas with the community