name: 💡 Feature Request
description: Suggest a new feature or capability for the system
title: "[FEATURE] "
labels: ["enhancement", "feature-request", "teacher-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 Feature Request
        
        Use this template to suggest new features or capabilities for the activity management system.
        Help us understand what you need and why it would be valuable for the school.

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: Briefly describe the new feature you'd like to see
      placeholder: e.g., "Email notifications when students sign up" or "Export activity rosters to PDF"
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem or Need
      description: What problem would this feature solve? What need does it address?
      placeholder: |
        e.g., "Teachers don't know when students sign up for their activities until they check the website"
        e.g., "Need to print attendance lists for activities but can't export the data"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: |
        e.g., "Send an email to the teacher whenever a student signs up or cancels"
        e.g., "Add an 'Export to PDF' button on each activity that creates a printable roster"
    validations:
      required: true

  - type: dropdown
    id: target-users
    attributes:
      label: Who would use this feature?
      description: Select the primary users who would benefit
      options:
        - Teachers only
        - Students only
        - Both teachers and students
        - School administrators
        - Parents
        - Everyone
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often would this feature be used?
      description: Help us understand the usage pattern
      options:
        - Daily
        - Weekly
        - Monthly
        - Occasionally (few times per semester)
        - Rarely (once per semester or less)
    validations:
      required: true

  - type: textarea
    id: user-workflow
    attributes:
      label: User Workflow
      description: Walk through how a user would interact with this feature step by step
      value: |
        1. User goes to...
        2. User clicks...
        3. System shows...
        4. User enters...
        5. System does...
        6. User sees...
      placeholder: Replace with the actual workflow for your feature
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this feature?
      description: Help us prioritize development
      options:
        - High - Would significantly improve daily operations
        - Medium - Would be helpful but not critical
        - Low - Nice to have enhancement
    validations:
      required: true

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How would you measure if this feature is successful?
      placeholder: |
        e.g., "Teachers respond to student signups faster"
        e.g., "Less time spent on administrative tasks"
        e.g., "Fewer questions from parents about activity status"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Are there other ways to solve this problem? What have you tried?
      placeholder: |
        e.g., "Currently checking the website manually every day"
        e.g., "Using spreadsheets to track attendance separately"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What should the completed feature do? Be specific about functionality.
      value: |
        - [ ] Feature is accessible from the main interface
        - [ ] Feature works reliably without errors
        - [ ] Feature provides clear feedback to users
        - [ ] Feature doesn't break existing functionality
        - [ ] Feature is easy to understand and use
      placeholder: Add specific criteria for your feature...
    validations:
      required: true

  - type: checkboxes
    id: considerations
    attributes:
      label: Implementation Considerations
      description: Any special requirements or constraints?
      options:
        - label: Should work on mobile devices
        - label: Needs to be accessible for users with disabilities
        - label: Should integrate with external systems (email, calendar, etc.)
        - label: Requires data export/import capabilities
        - label: Needs to be simple for non-technical users
        - label: Should maintain data privacy and security

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other information that would help with implementation?
      placeholder: |
        e.g., "This is required for state compliance"
        e.g., "Parents have requested this at PTA meetings"
        e.g., "Other schools in the district have similar features"

  - type: markdown
    attributes:
      value: |
        ## 💡 Implementation Hints
        
        **For the developer implementing this:**
        - Consider if this feature requires database schema changes
        - Evaluate if external services (email, PDF generation) are needed
        - Plan for error handling and user feedback
        - Consider security and privacy implications
        - Think about mobile responsiveness and accessibility
        - Estimate complexity and break into smaller tasks if needed
        
        **Technical Context:**
        - Backend: FastAPI with MongoDB database
        - Frontend: Vanilla HTML/CSS/JavaScript
        - Current features: activity management, user authentication, student registration
        - Keep the system simple and maintainable
        - Follow existing code patterns and conventions